@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU1NDYwNzZ9.kyRQAm_nNIUDMNy4AkhcXuRrkm_Dw3QkeD4vmLA3LSc

@hostname = http://localhost:3000
### Users create (signup)
  POST {{hostname}}/users
  Content-Type: application/json

  {
    "handle": "ryan",
    "email": "ryan@gmail.com",
    "password": "password",
    "password_confirmation": "password"
  }


### Sessions create login

  POST {{hostname}}/sessions
  Content-Type: application/json

  {
    "email": "moo@gmail.com",
    "password": "password"
  }

### USERS SHOW
GET {{hostname}}/users/1
Content-Type: application/json
Authorization: Bearer {{jwt}}


### USERS UPDATE
PATCH {{hostname}}/users/1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "tag_ids": [2, 10, 16]
}

### USER DESTROY

DELETE {{hostname}}/users/4
Content-Type: application/json
Authorization: Bearer {{jwt}}


### TAGS INDEX
GET {{hostname}}/tags

### GAMES INDEX
GET {{hostname}}/games



### GAMES SHOW
GET {{hostname}}/games/6
Content-Type: application/json
Authorization: Bearer {{jwt}}