@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzQ0Mzg2NjN9.3X56edDH75XWlmtTU_4_Z1-SdHZFeFnco5uG5zj4BA4
@hostname = http://localhost:3000
### Users create (signup)
  POST {{hostname}}/users
  Content-Type: application/json

  {
    "handle": "forrest",
    "email": "forrest@gmail.com",
    "password": "password",
    "password_confirmation": "password"
  }


### Sessions create login

  POST {{hostname}}/sessions
  Content-Type: application/json

  {
    "email": "moo@gmail.com",
    "password": "password"
  }

### USERS SHOW
GET {{hostname}}/users/1

### USERS UPDATE
PATCH {{hostname}}/users/1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "image_url": "test",
  "stream_url": "moo.ttv",
  "bio": "im moo an evil wierd cat",
  "game_id": 3,
}
