### Users create (signup)
  POST http://localhost:3000/users
  Content-Type: application/json

  {
    "handle": "forrest",
    "email": "forrest@gmail.com",
    "password": "password",
    "password_confirmation": "password"
  }


  ### Sessions create login

  POST http://localhost:3000/sessions
  Content-Type: application/json

  {
    "email": "moo@gmail.com",
    "password": "password"
  }